model:
  base_learning_rate: 1.0e-4
  target: ldm.models.vanila_ae.Vanila_AE
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    n_embed: 8192
    lossconfig:
      target: ldm.modules.losses.Vanila

    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 2, 4] # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: True
    train:
      target: ldm.data.fundus.FundusSRTrain
      params:
        size: 256
        degradation: pil_nearest
        data_dir: /data1/fundus_dataset/inhouse_dataset
    validation:
      target: ldm.data.fundus.FundusSRValidation
      params:
        size: 256
        degradation: pil_nearest
        data_dir: /data1/fundus_dataset/inhouse_dataset
    test:
      target: ldm.data.fundus.FundusSRTest
      params:
        size: 256
        degradation: pil_nearest
        data_dir: /data1/fundus_dataset/inhouse_dataset

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        valtest_batch_frequency: 200
        max_images: 8
        increase_log_steps: True

  trainer:
    max_epochs: 30
    check_val_every_n_epoch: 1
    benchmark: True
    accumulate_grad_batches: 2
    precision: 16
    strategy: "ddp_spawn"
    sync_batchnorm: True
